{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mtchat.fullname" . }}
  labels:
    {{- include "mtchat.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.jwtSecret }}
  {{ .Values.secrets.secretKeys.jwtSecretKey }}: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.adminApiToken }}
  {{ .Values.secrets.secretKeys.adminApiTokenKey }}: {{ .Values.secrets.adminApiToken | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mtchat.fullname" . }}-postgresql
  labels:
    {{- include "mtchat.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}: {{ .Values.postgresql.auth.password | default (randAlphaNum 24) | quote }}
{{- end }}
---
{{- if and .Values.minio.enabled (not .Values.minio.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mtchat.fullname" . }}-minio
  labels:
    {{- include "mtchat.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-user: {{ .Values.minio.rootUser | quote }}
  root-password: {{ .Values.minio.rootPassword | default (randAlphaNum 24) | quote }}
{{- end }}
